
// FHN Store - script.js
const CART_KEY='fhn_cart_v1',USER_KEY='fhn_user_v1',ORDER_KEY='fhn_last_order_v1';
const ADMINS=[{name:'Fathan',ig:'fathan.ig',tiktok:'fathan.tiktok',wa:'+62 851-8933-9661',email:'fathanalmusthofa1987@gmail.com'},{name:'Admin 2',ig:'admin2.ig',tiktok:'admin2.tiktok',wa:'0812xxxx',email:'admin2@example.com'}];
const GAMES={'steal-a-brainrot':{label:'Steal a Brainrot',options:['Anomali Brainrot','Gamepass']},'grow-a-garden':{label:'Grow a Garden',options:['Seed','Pet','Gear','Event Shop','Joki Event']},'blox-fruit':{label:'Blox Fruit',options:['Gamepass','Fruit','Joki']},'car-driving-indonesia':{label:'Car Driving Indonesia',options:['Gamepass','Joki']},'plant-vs-brainrot':{label:'Plant vs Brainrot',options:['Brainrot','Gamepass Event','Plant']}};
const PRODUCTS=[{id:'sabr-1',game:'steal-a-brainrot',option:'Anomali Brainrot',title:'Anomali Pack',price:15000,desc:'Bundle anomali lengkap.'},{id:'sabr-2',game:'steal-a-brainrot',option:'Gamepass',title:'Gamepass Brainrot',price:25000,desc:'Akses premium.'},{id:'gag-1',game:'grow-a-garden',option:'Seed',title:'Rare Seed Pack',price:12000,desc:'Paket seed langka.'},{id:'gag-2',game:'grow-a-garden',option:'Pet',title:'Cute Pet',price:20000,desc:'Peliharaan lucu.'},{id:'gag-3',game:'grow-a-garden',option:'Gear',title:'Garden Gear',price:18000,desc:'Perlengkapan.'},{id:'gag-4',game:'grow-a-garden',option:'Event Shop',title:'Event Coins',price:22000,desc:'Koin event.'},{id:'gag-5',game:'grow-a-garden',option:'Joki Event',title:'Joki Event Service',price:45000,desc:'Joki event.'},{id:'bf-1',game:'blox-fruit',option:'Gamepass',title:'Blox Fruit Gamepass',price:30000,desc:'Gamepass.'},{id:'bf-2',game:'blox-fruit',option:'Fruit',title:'Random Fruit',price:35000,desc:'Buah langka.'},{id:'bf-3',game:'blox-fruit',option:'Joki',title:'Joki Blox Fruit',price:60000,desc:'Joki leveling.'},{id:'cdid-1',game:'car-driving-indonesia',option:'Gamepass',title:'CDID Premium',price:18000,desc:'Unlock mobil.'},{id:'cdid-2',game:'car-driving-indonesia',option:'Joki',title:'Joki CDID',price:40000,desc:'Joki CDID.'},{id:'pvb-1',game:'plant-vs-brainrot',option:'Brainrot',title:'Brainrot Pack',price:16000,desc:'Item brainrot.'},{id:'pvb-2',game:'plant-vs-brainrot',option:'Gamepass Event',title:'Event Gamepass',price:21000,desc:'Gamepass event.'},{id:'pvb-3',game:'plant-vs-brainrot',option:'Plant',title:'Defender Plant',price:14000,desc:'Plant defense.'}];
function qs(s,r=document){return r.querySelector(s)}function qsa(s,r=document){return Array.from(r.querySelectorAll(s))}function fmt(n){return Number(n).toLocaleString('id-ID')}
const Cart={get(){try{return JSON.parse(localStorage.getItem(CART_KEY))||[]}catch(e){return[]}},save(items){localStorage.setItem(CART_KEY,JSON.stringify(items));renderCartCount()},add(item){const c=this.get();const idx=c.findIndex(x=>x.id===item.id&&x.variant===item.variant);if(idx>-1)c[idx].qty+=item.qty;else c.push(item);this.save(c)},remove(id,variant){const c=this.get().filter(i=>!(i.id===id&&i.variant===variant));this.save(c)},clear(){localStorage.removeItem(CART_KEY);renderCartCount()}};
function renderCartCount(){const el=qs('#cartCount');if(!el)return;el.textContent=Cart.get().reduce((s,i)=>s+i.qty,0)}
const Auth={get(){try{return JSON.parse(localStorage.getItem(USER_KEY))}catch(e){return null}},set(u){localStorage.setItem(USER_KEY,JSON.stringify(u));renderAuth()},logout(){localStorage.removeItem(USER_KEY);renderAuth()}};
function renderAuth(){const box=qs('#authBox');if(!box)return;const u=Auth.get();if(u)box.innerHTML=`<div class="kv">Hi, <strong>${u.name}</strong></div> <button class="btn" id="logoutBtn">Logout</button>`;else box.innerHTML=`<div class="kv">Belum sign in</div>`;const b=qs('#logoutBtn');if(b)b.onclick=()=>Auth.logout()}
function renderSidebar(selected){const gameList=qs('#gameList');if(!gameList)return;gameList.innerHTML='';Object.entries(GAMES).forEach(([k,v])=>{const b=document.createElement('button');b.textContent=v.label;b.dataset.key=k;if(k===selected)b.classList.add('active');b.onclick=()=>selectGame(k);gameList.appendChild(b)});renderFilters(selected||Object.keys(GAMES)[0])}
function renderFilters(gameKey){const box=qs('#filters');if(!box)return;box.innerHTML='';const g=GAMES[gameKey];if(!g)return;const h=document.createElement('h4');h.textContent='Pilihan untuk '+g.label;box.appendChild(h);const list=document.createElement('div');list.className='filter-list';g.options.forEach(opt=>{const b=document.createElement('button');b.textContent=opt;b.onclick=()=>filterBy(gameKey,opt);list.appendChild(b)});box.appendChild(list)}
function getQuery(name){const u=new URL(location.href);return u.searchParams.get(name)}function setQuery(name,val){const u=new URL(location.href);u.searchParams.set(name,val);history.replaceState(null,'',u);return u.toString()}
function initHome(){const sel=getQuery('game')||'steal-a-brainrot';renderSidebar(sel);const feat=qs('#featured');if(!feat)return;feat.innerHTML='';PRODUCTS.slice(0,8).forEach(p=>{const d=document.createElement('div');d.className='card';d.innerHTML=`<div class="product-thumb">${p.option}</div><div class="p-title">${p.title}</div><div class="small">${p.option} • Rp ${fmt(p.price)}</div><div class="flex" style="justify-content:space-between;margin-top:8px"><div class="price">Rp ${fmt(p.price)}</div><div><button class="btn" onclick="goProduct('${p.id}')">Lihat</button></div></div>`;feat.appendChild(d)});renderAuth();renderCartCount()}
function initProducts(){const game=getQuery('game')||'steal-a-brainrot';renderSidebar(game);const grid=qs('#productGrid');if(!grid)return;grid.innerHTML='';PRODUCTS.filter(p=>p.game===game).forEach(p=>{const d=document.createElement('div');d.className='card';d.innerHTML=`<div class="product-thumb">${p.option}</div><div class="p-title">${p.title}</div><div class="small">${p.option}</div><div class="flex" style="justify-content:space-between;margin-top:8px"><div class="price">Rp ${fmt(p.price)}</div><div><button class="btn" onclick="goProduct('${p.id}')">Detail</button></div></div>`;grid.appendChild(d)});renderAuth();renderCartCount()}
function initProductDetails(){const id=getQuery('id');renderSidebar(getQuery('game')||'steal-a-brainrot');const box=qs('#pd');if(!box)return;const p=PRODUCTS.find(x=>x.id===id);if(!p){box.innerHTML='<div class="card">Produk tidak ditemukan</div>';return}box.innerHTML=`<div class="card"><div class="flex" style="gap:16px"><div style="flex:1"><div class="product-thumb">${p.option}</div></div><div style="flex:2"><h2>${p.title}</h2><div class="small">${p.option} • ${GAMES[p.game].label}</div><p class="kv">${p.desc}</p><div class="price">Rp ${fmt(p.price)}</div><div style="margin-top:12px" class="flex"><input id="qtyInput" class="input" type="number" value="1" min="1" style="width:90px"><button class="btn primary" id="addToCartBtn">Tambah ke Keranjang</button></div></div></div></div>`;qs('#addToCartBtn').onclick=()=>{const qty=parseInt(qs('#qtyInput').value)||1;Cart.add({id:p.id,title:p.title,price:p.price,variant:p.option,qty});alert('Berhasil ditambahkan ke keranjang');renderCartCount()};renderAuth();renderCartCount()}
function initCartPage(){renderSidebar(getQuery('game')||'steal-a-brainrot');const list=qs('#cartList');if(!list)return;const c=Cart.get();list.innerHTML='';if(c.length===0){list.innerHTML='<div class="card">Keranjang kosong</div>';return}c.forEach(item=>{const row=document.createElement('div');row.className='card';row.innerHTML=`<div class="flex" style="justify-content:space-between"><div><strong>${item.title}</strong><div class="kv">${item.variant}</div></div><div>Rp ${fmt(item.price)} x ${item.qty}</div></div><div style="margin-top:8px"><button class="btn" onclick="removeFromCart('${item.id}','${item.variant}')">Hapus</button></div>`;list.appendChild(row)});qs('#checkoutBtn')?.addEventListener('click',()=>location.href='checkout.html');renderAuth();renderCartCount()}
function initCheckout(){renderSidebar(getQuery('game')||'steal-a-brainrot');const summary=qs('#summary');if(!summary)return;const c=Cart.get();if(c.length===0){summary.innerHTML='<div class="card">Keranjang kosong</div>';qs('#payForm').style.display='none';return}const total=c.reduce((s,i)=>s+i.price*i.qty,0);summary.innerHTML=`<div class="card"><h4>Ringkasan</h4>${c.map(i=>`<div class="flex" style="justify-content:space-between"><div>${i.title} (${i.variant}) x${i.qty}</div><div>Rp ${fmt(i.price*i.qty)}</div></div>`).join('')}<hr style="border:none;border-top:1px solid rgba(11,26,43,0.06);margin:10px 0"><div class="flex" style="justify-content:space-between"><strong>Total</strong><strong>Rp ${fmt(total)}</strong></div></div>`;const adminBox=qs('#adminBox');if(adminBox)adminBox.innerHTML=`<div class="card"><h4>Kontak Admin</h4>${ADMINS.map(a=>`<div class="kv"><strong>${a.name}</strong><br>IG: ${a.ig} • Tiktok: ${a.tiktok}<br>WA: ${a.wa}<br>Email: ${a.email}</div>`).join('<hr style="border:none;border-top:1px solid rgba(11,26,43,0.06);margin:8px 0">')}</div>`;qs('#payForm')?.addEventListener('submit',(e)=>{e.preventDefault();const custWA=qs('#custWA').value.trim();if(!custWA){alert('Masukkan nomor WhatsApp pelanggan (wajib)');return}const name=qs('#nameInput')?.value.trim()||'';const order={id:'ORD'+Date.now(),name,custWA,items:c,total,status:'queued',created:Date.now()};localStorage.setItem(ORDER_KEY,JSON.stringify(order));Cart.clear();location.href='order-status.html?order='+order.id});renderAuth();renderCartCount()}
function initSending(){renderSidebar(getQuery('game')||'steal-a-brainrot');const box=qs('#sendingBox');if(!box)return;const raw=JSON.parse(localStorage.getItem(ORDER_KEY)||'null');if(!raw){box.innerHTML='<div class="card">Tidak ada pesanan terakhir.</div>';return}box.innerHTML=`<div class="card"><h4>Order ${raw.id}</h4><div class="kv">Status: <strong id="statusText">${raw.status}</strong></div><div class="kv">Nomor WA Pelanggan: ${raw.custWA}</div><div style="margin-top:8px"><button class="btn" id="refreshStatus">Refresh Status</button></div></div>`;qs('#refreshStatus').onclick=()=>{if(raw.status==='queued')raw.status='processing';else if(raw.status==='processing')raw.status='shipped';localStorage.setItem(ORDER_KEY,JSON.stringify(raw));initSending()};renderAuth();renderCartCount()}
function initAdmin(){renderSidebar();const box=qs('#ordersBox');if(!box)return;let ok=sessionStorage.getItem('fhn_admin_ok');if(!ok){const pw=prompt('Masukkan password admin:');if(pw==='fathanadmin'){sessionStorage.setItem('fhn_admin_ok','1');ok='1'}else{box.innerHTML='<div class="card">Akses ditolak</div>';return}}const order=JSON.parse(localStorage.getItem(ORDER_KEY)||'null');if(!order){box.innerHTML='<div class="card">Belum ada pemesanan</div>';return}box.innerHTML=`<div class="card"><h4>Order ${order.id}</h4><div class="kv">Nama: ${order.name||'-'}</div><div class="kv">WA Pelanggan: ${order.custWA}</div><div class="kv">Total: Rp ${fmt(order.total)}</div><div class="kv">Status: <strong id="admStatus">${order.status}</strong></div><div style="margin-top:8px"><button class="btn" id="toProc">Tandai Processing</button> <button class="btn" id="toShip">Tandai Terkirim</button></div></div>`;qs('#toProc').onclick=()=>{order.status='processing';localStorage.setItem(ORDER_KEY,JSON.stringify(order));initAdmin()};qs('#toShip').onclick=()=>{order.status='shipped';localStorage.setItem(ORDER_KEY,JSON.stringify(order));initAdmin()};renderAuth();renderCartCount()}
function initContact(){renderSidebar();const cbox=qs('#contactBox');if(!cbox)return;cbox.innerHTML=ADMINS.map(a=>`<div class="card"><h4>${a.name}</h4><div class="kv">IG: ${a.ig}</div><div class="kv">Tiktok: ${a.tiktok}</div><div class="kv">No WA: ${a.wa}</div><div class="kv">Gmail: ${a.email}</div></div>`).join('');renderAuth();renderCartCount()}
function initLogin(){renderSidebar();renderAuth();qs('#waSendBtn')?.addEventListener('click',()=>{const p=qs('#waPhone').value.trim();if(!p){alert('Masukkan nomor WA');return}qs('#waCodeBox').style.display='block';alert('Kode verifikasi (simulasi): 123456')});qs('#waVerifyBtn')?.addEventListener('click',()=>{const code=qs('#waCode').value.trim();if(code==='123456'){Auth.set({name:'WA User',method:'wa'});location.href='index.html'}else alert('Kode salah (harus 123456)')});qs('#emailSendBtn')?.addEventListener('click',()=>{const e=qs('#emailInput').value.trim();if(!e){alert('Masukkan email');return}qs('#emailCodeBox').style.display='block';alert('Kode verifikasi email (simulasi): 123456')});qs('#emailVerifyBtn')?.addEventListener('click',()=>{const code=qs('#emailCode').value.trim();if(code==='123456'){Auth.set({name:'Email User',method:'email'});location.href='index.html'}else alert('Kode salah (harus 123456)')});qs('#googleBtn')?.addEventListener('click',()=>{Auth.set({name:'Google User',method:'google'});location.href='index.html'})}
function selectGame(key){setQuery('game',key);renderSidebar(key);if(document.body.dataset.page==='products')initProducts()}
function filterBy(game,opt){setQuery('game',game);if(document.body.dataset.page!=='products')location.href='products.html';else initProducts();alert('Filter dipilih: '+opt)}
function goProduct(id){location.href='product-details.html?id='+id}
function removeFromCart(id,variant){Cart.remove(id,variant);if(document.body.dataset.page==='cart')initCartPage()}
document.addEventListener('DOMContentLoaded',()=>{const page=document.body.dataset.page;renderAuth();renderCartCount();if(page==='home')initHome();if(page==='products')initProducts();if(page==='product-details')initProductDetails();if(page==='cart')initCartPage();if(page==='checkout')initCheckout();if(page==='sending')initSending();if(page==='admin')initAdmin();if(page==='contact')initContact();if(page==='login')initLogin()});window.goProduct=goProduct;window.removeFromCart=removeFromCart;window.selectGame=selectGame;window.filterBy=filterBy;
